# Generated by Django 6.0.2 on 2026-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Mexican', 'Mexican'), ('Italian', 'Italian'), ('American', 'American'), ('Middle Eastern', 'Middle Eastern'), ('Indian', 'Indian'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=20),
        ),
    ]
