# Generated by Django 6.0.2 on 2026-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Kitchen', 'In Kitchen'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered Pending', 'Delivered Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
