# Generated by Django 6.0.2 on 2026-02-07 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name'], 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_quantity',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_recipe_uses', to='home.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Used', 'Used - Order'), ('Adjusted', 'Manual Adjustment'), ('Returned', 'Returned'), ('Damaged', 'Damaged/Wasted')], max_length=20)),
                ('quantity_changed', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.inventoryitem')),
            ],
            options={
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_bom', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Recipe',
                'verbose_name_plural': 'Menu Item Recipes',
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_menus', to='home.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='home.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Ingredient',
                'unique_together': {('menu_item', 'inventory_item')},
            },
        ),
    ]
