# Generated by Django 6.0.2 on 2026-02-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_remove_order_order_id_remove_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='spice_level',
        ),
    ]
