# Generated by Django 6.0.2 on 2026-03-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='inventory_item',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
